public class ResourceRequest {
    public List<ResourceInfo> resources;
    public class ResourceInfo{    
    Public String resource_type;
    Public String added_by;
    Public String First_Name;
    Public String Title;
    Public String Last_Name;
    Public String Resource_code;
    Public String Resource_Class;
    Public Integer company_id;
    Public Integer default_profit_ctr_id;
    Public DateTime date_added;
    Public String Resource_CSID;
    Public String employee_ID;
    Public String modified_by;
    Public DateTime date_modified;
    Public String resource_status;
    }
}